apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: arathia
build:
  artifacts:
    - image: arathia
      docker:
        dockerfile: deploy/docker/Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
      - name: arathia
        chartPath: deploy/helm/arathia
        namespace: ecosystem
        createNamespace: true
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED_arathia}}"
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
