from domain.events import Climate

OCEAN = "."
OCEAN_COLOUR = "#00AFAF"

CONTINENTS = ("Northsaw", "Kuerigo", "Eastern Isles")

REGIONS = [
    (
        "b", "Boring Tundra", "Northsaw", "#8B5A2B",
        Climate(terrain="tundra", min_temperature=-25, max_temperature=8, rainfall="low"),
    ),
    (
        "c", "Chillcap", "Northsaw", "#1D46B4",
        Climate(terrain="ice cap", min_temperature=-40, max_temperature=-8, rainfall="low"),
    ),
    (
        "s", "Shard Forest", "Northsaw", "#B98FD9",
        Climate(terrain="crystal forest", min_temperature=-20, max_temperature=2, rainfall="low"),
    ),
    (
        "w", "Wailing Firth", "Northsaw", "#3A7D3A",
        Climate(terrain="cold estuary", min_temperature=-6, max_temperature=12, rainfall="torrential"),
    ),
    (
        "k", "Korees", "Kuerigo", "#B0713C",
        Climate(terrain="mountain", min_temperature=-12, max_temperature=14, rainfall="moderate"),
    ),
    (
        "t", "Trynwyn", "Kuerigo", "#2F3A17",
        Climate(terrain="mountain valleys", min_temperature=4, max_temperature=18, rainfall="high"),
    ),
    (
        "v", "Wyldvale", "Kuerigo", "#7B3FC7",
        Climate(terrain="vale", min_temperature=6, max_temperature=22, rainfall="moderate"),
    ),
    (
        "l", "Lominasa", "Kuerigo", "#B9CEFF",
        Climate(terrain="harbour city", min_temperature=2, max_temperature=24, rainfall="moderate"),
    ),
    (
        "r", "Ranatis", "Kuerigo", "#DDD066",
        Climate(terrain="desert", min_temperature=8, max_temperature=46, rainfall="arid"),
    ),
    (
        "d", "Doreidrassil", "Kuerigo", "#6A4E8C",
        Climate(terrain="enchanted forest", min_temperature=8, max_temperature=24, rainfall="high"),
    ),
    (
        "y", "Yoonhye Forest", "Eastern Isles", "#C1571E",
        Climate(terrain="autumn forest", min_temperature=4, max_temperature=26, rainfall="moderate"),
    ),
    (
        "g", "Tyrglen", "Eastern Isles", "#7A4D2A",
        Climate(terrain="highland glen", min_temperature=0, max_temperature=18, rainfall="moderate"),
    ),
    (
        "m", "Morghaan", "Eastern Isles", "#1E6B1E",
        Climate(terrain="steppe", min_temperature=-8, max_temperature=24, rainfall="low"),
    ),
    (
        "a", "Denn Arctogh", "Eastern Isles", "#EEF2F5",
        Climate(terrain="snowy valley", min_temperature=-35, max_temperature=-2, rainfall="low"),
    ),
    (
        "x", "The Wreck", "Eastern Isles", "#C75225",
        Climate(terrain="volcanic badlands", min_temperature=14, max_temperature=40, rainfall="arid"),
    ),
    (
        "n", "Wylenn", "Eastern Isles", "#45510B",
        Climate(terrain="woodland", min_temperature=2, max_temperature=20, rainfall="moderate"),
    ),
    (
        "o", "Gloamwoods", "Eastern Isles", "#141E1F",
        Climate(terrain="dark forest", min_temperature=0, max_temperature=16, rainfall="high"),
    ),
    (
        "f", "Stragglefaun", "Eastern Isles", "#CC6600",
        Climate(terrain="jungle", min_temperature=20, max_temperature=38, rainfall="torrential"),
    ),
    (
        "z", "Kagotsuma", "Eastern Isles", "#992E2E",
        Climate(terrain="volcanic coast", min_temperature=16, max_temperature=32, rainfall="high"),
    ),
]

REGION_MAP = """\
....................................................................................................
....................................................................................................
.................................bbbbbb..............wwwwwww........................................
...............................bbbbbbbbbb..........wwwwwwwwwwww.....................................
...............................bbbbbbbbbbbb......wwwwwwwwwwwwwww....................................
..............................bbbbbbbbbbbbcccccccwwwwwwwwwwwwwww....................................
..............................bbbbbbbbbbbbccccccccwwwwwwwwwwwwww....................................
..............................bbbbbbbbbbbcccccccccwwwwwwwwwwwwwww...................................
...............................bbbbbbbbbbccssssssccwwwwwwwwwwwwww...................................
.................................bbbbbbbcccsssssscccwwwwwwwwwwww....................................
...................................bbbbbccccssscccccwwwwwwwwwww.....................................
....................................bbbbcccccccccccccwwwwwwwww......................................
............................................cccccccccwwwww..........................................
....................................................................................................
..............................................................................y.....................
.............................................................................yyyy...................
...........................................................................yyyyyyy..................
...........................................................................yyyyyyyy.................
......................kkkk...............................................yyyyyyyyyy.................
...................kkkkkkkkkk.....dddd.................................yyyyyyyyyggg.................
..................kkkkkkkkkkttt.dddddddd..............................yyyyyyyyygggg.................
..................kkkkkkkkktttt..ddddddd............................yyyyyyyyygggggg.................
.................kkkkkkkkktttttt.dddddd............................yyyyyyyyyygggggg.................
................kkkkkkkktttttttt..................................yyyyyyyyyyygggggg.................
...............kkkkkkkkttttttttt..................................yyyyyymmmmmmmmmmm.................
...............kkkkkkttttttttttt.................................yyyyyymmmmmmmmmmmm.................
...............kkkkktttttttttttt..................................yyyy.mmmmmmmmmmm..................
..............vvvvvvvvvvvvvtttt...................................yyy.....mmmmmmmm..................
..............vvvvvvvvvvvvvvvv............................................mmmmmmm...................
..............vvvvvvvvvvvvvvv.........................................aaaaaaxxxxxx..................
.............vvvvvvvvvvvvvvvv........................................aaaaaaxxxxxxxx.................
.............rrrrvvvvvvvvvvv.........................................aaaaaaxxxxxxxx.................
............rrrrrrrrrrrrrlll........................................aaaaaaaxxxxxxx..................
............rrrrrrrrrrrrrlll........................................aaaaaaaaxxxxxx..................
............rrrrrrrrrrrrrrr.........................................aaaaaaaaxxxxxx..................
............rrrrrrrrrrrrrrr..........................................nnnnnnnnnnxx...................
............rrrrrrrrrrrrrrr.........................................nnnnnnnnnnnnn...................
.............rrrrrrrrrrrrrr........................................oonnnnnnnnnnn....................
.............rrrrrrrrrrrrrrr.......................................ooooooooooo......................
..............rrrrrrrrrrrrrr........................................ooooooooo.......................
...............rrrrrrrrrrrrr..........................................fffffff................zzzz...
................rrrrrrrrrrr..........................................fffffff...............zzzzzz...
.................rrrrrrrrrr..........................................ffffff...............zz...zz...
.....................rrrrrr..........................................f.........................zz...
..............................................................................................zzz...
............................................................................................zzz.....
............................................................................................zz......
............................................................................................z.......
....................................................................................................
....................................................................................................
"""

MAP_ROWS = REGION_MAP.splitlines()
HEIGHT = len(MAP_ROWS)
WIDTH = len(MAP_ROWS[0])
