apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
stringData:
  postgres-user: {{ .Values.credentials.postgresUser | quote }}
  postgres-password: {{ .Values.credentials.postgresPassword | quote }}
  rabbitmq-user: {{ .Values.credentials.rabbitmqUser | quote }}
  rabbitmq-password: {{ .Values.credentials.rabbitmqPassword | quote }}
  amqp-url: amqp://{{ .Values.credentials.rabbitmqUser }}:{{ .Values.credentials.rabbitmqPassword }}@rabbitmq:5672/
{{- range .Values.databases }}
  {{ . }}-database-url: postgresql+asyncpg://{{ $.Values.credentials.postgresUser }}:{{ $.Values.credentials.postgresPassword }}@{{ . }}-db:5432/{{ . }}
{{- end }}
