apiVersion: apps/v1
kind: Deployment
metadata:
  name: almanac
  namespace: ecosystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: almanac
  template:
    metadata:
      labels:
        app: almanac
    spec:
      containers:
        - name: almanac
          image: ecosystem/almanac:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: almanac-database-url
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: amqp-url
            - name: GENESIS_URL
              value: http://genesis:8000
            - name: TICK_SECONDS
              value: "2"
