debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.database.user=dev
debezium.source.database.password=dev
debezium.source.plugin.name=pgoutput
debezium.source.publication.autocreate.mode=filtered
debezium.source.table.include.list=public.outbox
debezium.source.tombstones.on.delete=false
debezium.source.snapshot.mode=no_data

debezium.transforms=outbox
debezium.transforms.outbox.type=io.debezium.transforms.outbox.EventRouter
debezium.transforms.outbox.route.by.field=routing_key
debezium.transforms.outbox.route.topic.replacement=$${routedByValue}
debezium.transforms.outbox.table.expand.json.payload=true

debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.username=dev
debezium.sink.rabbitmq.connection.password=dev
debezium.sink.rabbitmq.exchange=world.events
debezium.sink.rabbitmq.routingKey.source=topic

debezium.format.value.schemas.enable=false
debezium.format.key.schemas.enable=false
