kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ecosystem
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 18810
        protocol: TCP
      - containerPort: 30081
        hostPort: 18813
        protocol: TCP
      - containerPort: 30672
        hostPort: 18812
        protocol: TCP
      - containerPort: 30567
        hostPort: 18811
        protocol: TCP
  - role: worker
  - role: worker
