{{- range .Values.databases }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-{{ . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-{{ . }}
  template:
    metadata:
      labels:
        app: debezium-{{ . }}
    spec:
      containers:
        - name: debezium
          image: {{ $.Values.debezium.image }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DEBEZIUM_SOURCE_DATABASE_HOSTNAME
              value: {{ . }}-db
            - name: DEBEZIUM_SOURCE_DATABASE_DBNAME
              value: {{ . }}
            - name: DEBEZIUM_SOURCE_TOPIC_PREFIX
              value: {{ . }}
            - name: DEBEZIUM_SOURCE_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: postgres-user
            - name: DEBEZIUM_SOURCE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: postgres-password
            - name: DEBEZIUM_SINK_RABBITMQ_CONNECTION_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: rabbitmq-user
            - name: DEBEZIUM_SINK_RABBITMQ_CONNECTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: rabbitmq-password
          volumeMounts:
            - name: config
              mountPath: /debezium/config
          readinessProbe:
            httpGet:
              path: /q/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /q/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: debezium
{{- end }}
